columns:
  - LIMIT_BAL
  - AGE
  - BILL_AMT_SEPT
  - BILL_AMT_AUG
  - BILL_AMT_JUL
  - BILL_AMT_JUN
  - BILL_AMT_MAY
  - BILL_AMT_APR
  - PAY_AMT_SEPT
  - PAY_AMT_AUG
  - PAY_AMT_JUL
  - PAY_AMT_JUN
  - PAY_AMT_MAY
  - PAY_AMT_APR
  - Default_Pay
  - SEX_MALE
  - EDUCATION_Graduate_School
  - EDUCATION_High_School
  - EDUCATION_University
  - MARRIAGE_Married
  - MARRIAGE_Single
  - PAY_SEPT_2MDelay
  - PAY_SEPT_3MDelay
  - PAY_SEPT_4MDelay
  - PAY_SEPT_5MDelay
  - PAY_SEPT_6MDelay
  - PAY_SEPT_7MDelay
  - PAY_SEPT_8MDelay
  - PAY_SEPT_No_Consumption
  - PAY_SEPT_Paid_In_Full
  - PAY_SEPT_Revolving_Credit
  - PAY_AUG_2MDelay
  - PAY_AUG_3MDelay
  - PAY_AUG_4MDelay
  - PAY_AUG_5MDelay
  - PAY_AUG_6MDelay
  - PAY_AUG_7MDelay
  - PAY_AUG_8MDelay
  - PAY_AUG_No_Consumption
  - PAY_AUG_Paid_In_Full
  - PAY_AUG_Revolving_Credit
  - PAY_JUL_2MDelay
  - PAY_JUL_3MDelay
  - PAY_JUL_4MDelay
  - PAY_JUL_5MDelay
  - PAY_JUL_6MDelay
  - PAY_JUL_7MDelay
  - PAY_JUL_8MDelay
  - PAY_JUL_No_Consumption
  - PAY_JUL_Paid_In_Full
  - PAY_JUL_Revolving_Credit
  - PAY_JUN_2MDelay
  - PAY_JUN_3MDelay
  - PAY_JUN_4MDelay
  - PAY_JUN_5MDelay
  - PAY_JUN_6MDelay
  - PAY_JUN_7MDelay
  - PAY_JUN_8MDelay
  - PAY_JUN_No_Consumption
  - PAY_JUN_Paid_In_Full
  - PAY_JUN_Revolving_Credit
  - PAY_MAY_3MDelay
  - PAY_MAY_4MDelay
  - PAY_MAY_5MDelay
  - PAY_MAY_6MDelay
  - PAY_MAY_7MDelay
  - PAY_MAY_8MDelay
  - PAY_MAY_No_Consumption
  - PAY_MAY_Paid_In_Full
  - PAY_MAY_Revolving_Credit
  - PAY_APR_3MDelay
  - PAY_APR_4MDelay
  - PAY_APR_5MDelay
  - PAY_APR_6MDelay
  - PAY_APR_7MDelay
  - PAY_APR_8MDelay
  - PAY_APR_No_Consumption
  - PAY_APR_Paid_In_Full
  - PAY_APR_Revolving_Credit